#global
seed: 2434
device: 'cuda:0'
save_root: test/
exp_name: recon
dataset: 'custom'
body_type: 'smplx'
ckpt: '/home/yqw/home/zsh/final_project/logs/THuman/Train_4v/20250428-140034/model-0950.pth'
#dataset
data_root: '/home/yqw/home/zsh/final_project/data/example/mv'
GT_root: '/home/yqw/home/zsh/final_project/data/THuman/THuman_obj'
img_size: 512
num_samples: 20480
white_bg: True
aug_jitter: False
views: 4
# test
subdivide: True
save_uv: False
clean_mesh_flag: True
mcube_res: 256

#feature_extractor:
use_trans: True

#network:
pos_dim: 8
feat_dim: 64
num_layers: 5
hidden_dim: 256
skip: [2,3,4]
activation: 'lrelu'
layer_type: 'none'
#embedder:
shape_freq: 0
color_freq: 0

#validation:
grid_size: 512
