#global
seed: 2434
save_root: logs/THuman
exp_name: Train_4v
device: 'cuda:3'
dataset: 'THuman'
distribute: True
#feature_extractor:
use_trans: True

#dataset
data_root: 'data/THuman/THuman_dataset'
img_size: 512
num_samples: 20480
white_bg: False
aug_jitter: False
views: 4


#optimizer
lr_decoder: 0.001
lr_encoder: 0.0001
beta1: 0.5
beta2: 0.999
weight_decay: 0.0

#scheduler
lr_scheduler: 'constant_with_warmup'
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
max_grad_norm: 1.0

#train
epochs: 1000
batch_size: 12
workers: 12
save_every: 50
log_every: 41
log_level: 20
resume: '/home/yqw/home/zsh/final_project/logs/THuman/Train_4v/20250427-133708/model-0200.pth'

#network:
pos_dim: 8
feat_dim: 64
num_layers: 5
hidden_dim: 256
skip: [2,3,4]
activation: 'lrelu'
layer_type: 'none'

#embedder:
shape_freq: 0
color_freq: 0

#losses:
lambda_sdf: 10.
lambda_rgb: 1.
lambda_nrm: 1.
lambda_2D: 1.
use_mask: False
use_pred_nrm: False

#validation:
valid: True
valid_folder: '../data/examples'
valid_every: 50
subdivide: True
grid_size: 256
erode_iter: 0
num_valid_samples: 5

#wandb:
wandb: False
wandb_id: None
wandb_name: 'train-recon'
